# Support launching the development container
services:
  develop-base:
    build:
      context: .
      dockerfile: Dockerfile
      target: ros-develop
      args:
        - USERNAME=${USERNAME:-dev}
        - USER_UID=${USER_UID:-501}
        - USER_GID=${USER_GID:-501}
        - ROS_DISTRO=${ROS_DISTRO:-iron}
    # Ensures signals are actually passed and reaped in the container for shutdowns.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#init
    init: true
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    volumes:
      - ${ROS_WORKSPACE:-/dev/null}:/home/${USERNAME:-dev}/ws
      - ${HOME}/.ccache/:/home/${USERNAME:-dev}/.ccache:rw

  develop:
    extends: develop-base
    container_name: ${ROS_WORKSPACE_NAME:-ros}-develop-container
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: sleep infinity

  develop-mac:
    extends: develop-base
    container_name: ${ROS_WORKSPACE_NAME:-ros}-develop-container-mac
    # Allows graphical programs in the container.
    # NOTE: Gazebo is still broken on native macos :(, but this seems to work with Qt and RViz
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    volumes:
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    command: sleep infinity
